#163446117 Voting functionality
dbytecoderc/Questioner pull request #40
Opened 2019-01-26 06:39 UTC by dbytecoderc

#### What does this PR do?
> - This PR adds the functionality to enable user indicate if they are going to attend a meetup

#### Description of Task to be completed?
> - Have the PATCH `/api/v1/questions/:id/upvote` and `/api/v1/questions/:id/downvote` route working
#### How should this be manually tested?
> - Clone the repo and run `npm install` to install dependencies.
> - Download and install postgresql from this [link](https://www.postgresql.org/)
> - Setup postgreql using this [guide](https://www.postgresql.org/docs/10/runtime.html)
> - run `npm migrate` to create the tables
> - run `npm start:dev` to start server
> - check the `server/test/testData` folder route for the input formats and proceed to testing with postman.

#### What are the relevant pivotal tracker stories?
> - `#163446117`

#### NB
> - I have addressed the concerns in the last PR here

2019-01-26 22:27 UTC, Veraclins requested changes
@dbytecoderc Good job as usual. Just a few points of note for which I have added comments. Let me know what you think about them. Another thing, you need to pay attention to your method names. As a general rule, your method names should say what they do e.g. `upvoteQuestion` but what does `responseToMeetup` do? Also, attaching the Module name to the methods in the module is an unnecessary duplication. `upvoteQuestion` could simply be `upvote`. The Question class would obviously contain only methods related to the Question model. This way when calling them, you can simple do:
`Question.upvote` instead of `Question.upvoteQuestion`
`Question.getById` instead of `Question.getQuestionById`
etc.

2019-01-26 22:27 UTC, Veraclins commented on server/app.js
> +  message: 'This route does not exist you might want to check your route specification on postman or check your route configurations.',
Like I have always told you, you are designing for the end user who is mostly non-technical. Do you think everybody knows what is route let alone postman? Have you visited any site before and received this kind of error message? And do you intend to change this when you implement the frontend or will I be checking postman on the frontend too?

2019-01-26 22:27 UTC, Veraclins commented on server/controller/questions.js
> +    const vote = `${userActionArray[userActionArray.length - 1]}d`;
Can you explain what is happening here and why this is necessary?

2019-01-26 22:27 UTC, Veraclins commented on server/models/question.js
> +  static async createVotesTable(userId, questionId, vote) {
Why is the name createVotesTable? Are you creating the table here?

2019-01-26 22:27 UTC, Veraclins commented on server/controller/questions.js
> +    const voted = await QuestionModel.ifVoted(userId, questionId);
Does this mean I can't change my vote? What if I wanted to upvote and mistakenly downvote a question?

2019-01-26 22:27 UTC, Veraclins commented on server/controller/rsvp.js
> +    if (result.length === 0) return successResponse(res, 200, 'You have not joined any meetups yet.', result);
Is this a successful request?

2019-01-26 23:26 UTC, oldmonad commented on server/controller/questions.js
> +    const vote = `${userActionArray[userActionArray.length - 1]}d`;
I extracted the request URL, converted it to an array and assigned the array to the userActionArray variable then I proceeded to getting the last value which is 'upvote' or 'downvote' and concatenated the letter 'd' to it to make it a past tense before creating a table containing the user id, question id and the 'past tense' i created, So the whole idea is to create a row on that votes table containing the user id and question  as a unique occurrence, the rubric didn't specify if a user can change his/her vote status after voting although I planned implementing that, If you check my questions model you would see I have some methods that is supposed to help with that functionality but at the time of writing this I have not yet figured it out

2019-01-26 23:31 UTC, dbytecoderc commented on server/controller/rsvp.js
> +    if (result.length === 0) return successResponse(res, 200, 'You have not joined any meetups yet.', result);
It is a successful request but I should have sent a 204 status code response to signify a no content response

2019-01-26 23:31 UTC, dbytecoderc commented on server/controller/questions.js
> +    const voted = await QuestionModel.ifVoted(userId, questionId);
the rubric didn't specify if a user can change his/her vote status after voting although I planned implementing that, If you check my questions model you would see I have some methods that is supposed to help with that functionality but at the time of writing this I have not yet figured it out

2019-01-26 23:41 UTC, oldmonad commented on server/models/question.js
> +  static async createVotesTable(userId, questionId, vote) {
Yeah this table is supposed to serve as a reference point to check the user vote status, at which point I am supposed to update the status to enable the user make another action, for instance if a user has upvoted and wants to downvote I would check this table to know his status and proceed to downvote the question, if he has upvoted and wants to upvote again then i would let him know that he cant upvote twice

2019-01-27 11:04 UTC, Veraclins commented on server/controller/questions.js
> +    const voted = await QuestionModel.ifVoted(userId, questionId);
You need to own the product and make it as realistic as possible. The rubrics just gives you the bare minimums, it is on you then to provide features that will improve user experience and I think that allowing users the ability to change their vote is cool to have.

2019-01-27 11:09 UTC, Veraclins commented on server/controller/questions.js
> +    const vote = `${userActionArray[userActionArray.length - 1]}d`;
I figured but do you think that is necessary? What stops you from just passing the string `upvoted` here and `downvoted` in the other method. In programming, the simplest way is always the best way. Will there ever be a time when this value is noted upvoted?

2019-01-27 11:13 UTC, Veraclins commented on server/controller/rsvp.js
> +    if (result.length === 0) return successResponse(res, 200, 'You have not joined any meetups yet.', result);
How is a request where I didn't get what I requested for a successful request? You must stop thinking from the perspective of the application or developer and start thinking from the perspective of the user. A request is only successful if I get exactly what I requested for.

2019-01-27 11:15 UTC, dbytecoderc commented on server/controller/questions.js
> +    const vote = `${userActionArray[userActionArray.length - 1]}d`;
Ok i think I know a way to make it simpler

2019-01-27 11:18 UTC, Veraclins commented on server/models/question.js
> +  static async createVotesTable(userId, questionId, vote) {
I beg to disagree, there is a difference between creating a TABLE and creating a RECORD in a table. I believe the latter is the case here. `createVoteTable` cannot be the right method name here.

2019-01-27 11:22 UTC, dbytecoderc commented on server/models/question.js
> +  static async createVotesTable(userId, questionId, vote) {
Ooh that's true it skipped my mind totally, I would change that to `createVoteRecord` then

2019-01-31 13:08 UTC, merged